# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

# 参考
# https://qiita.com/yuta-shoji/items/60767d77bd78e4e5b714

ipa("./.build/TimeWatcher.ipa")
copyright("#{Time.now.year} stotic-dev") # コピーライト
price_tier(0) # アプリの価格
app_rating_config_path("./fastlane/metadata/app_store_rating_config.json") # アプリの年齢制限指定情報
# アプリの著作権情報
submission_information({
    content_rights_contains_third_party_content: true, # サードパーティ製コンテンツを含むか
    export_compliance_uses_encryption: false, # 
    export_compliance_encryption_updated: false,
    add_id_info_uses_idfa: false,
    add_id_info_serves_ads: false,
    add_id_info_tracks_action: false,
    add_id_info_tracks_install: false,
})
precheck_include_in_app_purchases(false) # アップ内課金の有無
submit_for_review(true) # 自動審査
automatic_release(false) # 自動配信
overwrite_screenshots(true) # スクリーンショットの上書き
force(true) # Upload前のHTMLレポートチェックのスキップ
reject_if_possible(true) # 審査中のビルドを上書きするかどうか