# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do |lane, options|
end

platform :ios do

  desc "do test"
  lane :test do |options|
    scan
  end

  desc "Upload to TestFlight"
  lane :beta do
    scan
    gym
    increment_build_number
    upload_beta
    commit_version_bump
    push_to_git_remote
  end

  #hidden from lanes,list,docs
  desc "Upload ipa for TestFlight"
  lane :upload_beta do |options|
    app_store_connect_api_key(
      key_id: ENV[APP_CONNECT_API_KEY_ID],
      issuer_id: ENV[APP_CONNECT_API_ISSUER_ID],
      key_content: ENV[APP_CONNECT_API_PRIVATE_KEY],
      duration: 1200,
    )
    upload_to_testflight(
      ipa: "./.build/TimeWatcher.ipa",
      demo_account_required: false,
      skip_waiting_for_build_processing: "true",
      beta_app_review_info: {
        contact_email: "taichis844@gmail.com",
        contact_first_name: "Taichi",
        contact_last_name: "Satou",
        contact_phone: "080-9754-8211",
        notes: "TimeWatcherの内部テスト"
      }
    )
  end
end

after_all do |lane, options|
end
