name: CD_Beta_Time_Watcher

on:
  pull_request:
    branches:
      - "release/*"
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_16.app
  WORKSPACE_PATH: TimerWatcherWorkspace.xcworkspace
  TARGET_SCHEME_NAME: TimeWatcher
  TARGET_TEST_PLAN_NAME: TimeWatcher

jobs:
  build:
    runs-on: macos-latest

    steps:
      # チェックアウト(リポジトリからソースコードを取得)
      - name: Check Out repository
        uses: actions/checkout@v3

      # Xcodeの一覧出力
      - name: Show Xcode list
        run: ls /Applications | grep 'Xcode'

      # Xcodeのバージョン指定
      - name: Select Xcode version
        run: sudo xcode-select -s $DEVELOPER_DIR

      # Xcodeのバージョン出力
      - name: Show Xcode version
        run: xcodebuild -version

      # Rudy製ライブラリのキャッシュ
      - name: Cache Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Rudy製ライブラリのインストール
      - name: Install Bundled Gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # SPMのライブラリのキャッシュ
      - name: Cache Swift Packages
        uses: actions/cache@v2
        with:
          path: SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('*.xcodeproj/project.xcworkspace/ xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-
      # TestFlight用にデプロイ
      - name: deploy
        run: set -o pipefail &&
          bundle exec fastlane beta --verbose
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          ENVIRONMENT: "CI"
          MATCH_FETCH_READ_ONLY_MODE: true
          SETUP_CI_PROVIDER: "travis"
