name: CI_Time_Watcher

on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_16.0.app
  WORKSPACE_PATH: TimerWatcherWorkspace.xcworkspace
  TARGET_SCHEME_NAME: TimeWatcher
  TARGET_TEST_PLAN_NAME: TimeWatcher
  GOOGLE_SERVICE_INFO_PLIST_PATH: TimeWatcherPrj/TimeWatcher/GoogleService-Info.plist

jobs:
  build:
    runs-on: macos-latest

    steps:
      # チェックアウト(リポジトリからソースコードを取得)
      - name: Check Out repository
        uses: actions/checkout@v3

      # Xcodeの一覧出力
      - name: Show Xcode list
        run: ls /Applications | grep 'Xcode'

      # Xcodeのバージョン指定
      - name: Select Xcode version
        run: sudo xcode-select -s ${{ env.DEVELOPER_DIR }}

      # Xcodeのバージョン出力
      - name: Show Xcode version
        run: xcodebuild -version

      # Rudy製ライブラリのキャッシュ
      - name: Cache Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Rudy製ライブラリのインストール
      - name: Install Bundled Gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # SPMのライブラリのキャッシュ
      - name: Cache Swift Packages
        uses: actions/cache@v2
        with:
          path: SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('*.xcodeproj/project.xcworkspace/ xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-

      # GoogleService-Info.plistの復元
      - name: Decode GoogleService-Info.plist
        run: |
          base64 -D ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_CONTENT }} -o ${{ env.GOOGLE_SERVICE_INFO_PLIST_PATH }}

      # ビルド
      - name: Xcode virify
        run: set -o pipefail &&
          xcodebuild
          -workspace ${WORKSPACE_PATH}
          -scheme ${TARGET_SCHEME_NAME}
          -testPlan ${TARGET_TEST_PLAN_NAME}
          -sdk iphonesimulator
          -configuration Debug
          -destination "platform=iOS Simulator,OS=17.2,name=iPhone 15 Pro"
          -clonedSourcePackagesDirPath SourcePackages
          -scmProvider xcode
          -allowProvisioningUpdates
          -skipPackagePluginValidation
          -parallel-testing-enabled NO
          clean test |
          bundle exec xcpretty
